---
apiVersion: v2
name: ibm-commonui-operator-app-cluster-scoped
description: A Helm chart for ibm-commonui-operator-app cluster scoped resources
type: application
version: "4.9.0"
appVersion: "4.9.0"
