scorecard:
  # Setting a global scorecard option
  bundle: deploy/olm-catalog/ibm-commonui-operator
  plugins:
    - basic:
        cr-manifest:
          - "deploy/crds/foundation.ibm.com_navconfiguration_cp4i_cr.yaml"
          - "deploy/crds/foundation.ibm.com_v1_navconfiguration_default_cr.yaml"
          - "deploy/crds/operators.ibm.com_v1alpha1_commonwebui_cr.yaml"
          - "deploy/crds/operators.ibm.com_v1alpha1_legacyheader_cr.yaml"
        csv-path: "deploy/olm-catalog/ibm-commonui-operator/1.1.0/ibm-commonui-operator.v1.1.0.clusterserviceversion.yaml"
    - olm:
        cr-manifest:
          - "deploy/crds/foundation.ibm.com_navconfiguration_cp4i_cr.yaml"
          - "deploy/crds/foundation.ibm.com_v1_navconfiguration_default_cr.yaml"
          - "deploy/crds/operators.ibm.com_v1alpha1_commonwebui_cr.yaml"
          - "deploy/crds/operators.ibm.com_v1alpha1_legacyheader_cr.yaml"
        csv-path: "deploy/olm-catalog/ibm-commonui-operator/1.1.0/ibm-commonui-operator.v1.1.0.clusterserviceversion.yaml"