# Documentation on available configuration
# https://cloud.ibm.com/docs/devsecops?topic=devsecops-cd-devsecops-apps-byoa
# https://cloud.ibm.com/docs/devsecops?topic=devsecops-custom-scripts

version: '1'
setup:
  skip: true
  image: icr.io/continuous-delivery/pipeline/pipeline-base-ubi:3.46
  script: |
    #!/usr/bin/env bash
    echo "Running setup stage"

detect-secrets:
  skip: true
  image: icr.io/continuous-delivery/pipeline/pipeline-base-ubi:3.46
  script: |
    #!/usr/bin/env bash
    echo "Running detect-secrets  stage"

test:
  skip: true
  abort_on_failure: false
  image: icr.io/continuous-delivery/pipeline/pipeline-base-ubi:3.46
  script: |
    #!/usr/bin/env bash
    echo "Running test stage"

compliance-checks:
  skip: true
  abort_on_failure: false
  image: icr.io/continuous-delivery/pipeline/pipeline-base-ubi:3.46
  script: |
    #!/usr/bin/env bash
    echo "Running compliance-checks stage"

finish:
  skip: true
  abort_on_failure: false
  image: icr.io/continuous-delivery/pipeline/pipeline-base-ubi:3.46
  script: |
    #!/usr/bin/env bash
    echo "Running test stage"