# Documentation on available configuration
# https://cloud.ibm.com/docs/devsecops?topic=devsecops-cd-devsecops-apps-byoa
# https://cloud.ibm.com/docs/devsecops?topic=devsecops-custom-scripts

version: '1'
setup:
  image: icr.io/continuous-delivery/pipeline/pipeline-base-ubi:3.46
  script: |
    #!/usr/bin/env bash
    echo "Running non-skippable setup stage"

detect-secrets:
  skip: true
  image: icr.io/continuous-delivery/pipeline/pipeline-base-ubi:3.46
  script: |
    #!/usr/bin/env bash
    echo "Running non-skippable detect-secrets stage"

test:
  skip: true
  abort_on_failure: false
  image: icr.io/continuous-delivery/pipeline/pipeline-base-ubi:3.46
  script: |
    #!/usr/bin/env bash
    echo "Running test stage"

peer-review:
  skip: true
  abort_on_failure: false
  image: icr.io/continuous-delivery/pipeline/pipeline-base-ubi:3.46
  script: |
    #!/usr/bin/env bash
    echo "Running peer-review stage"

static-scan:
  skip: true
  abort_on_failure: false
  image: icr.io/continuous-delivery/pipeline/pipeline-base-ubi:3.46
  script: |
    #!/usr/bin/env bash
    echo "Running static-scan stage"

compliance-checks:
  skip: true
  abort_on_failure: false
  image: icr.io/continuous-delivery/pipeline/pipeline-base-ubi:3.46
  script: |
    #!/usr/bin/env bash
    echo "Running compliance-checks stage"

containerize:
  abort_on_failure: false
  image: icr.io/continuous-delivery/pipeline/pipeline-base-ubi:3.46
  script: |
    #!/usr/bin/env bash
    echo "Running non-skippable containerize stage"

sign-artifact:
  abort_on_failure: false
  image: icr.io/continuous-delivery/pipeline/pipeline-base-ubi:3.46
  script: |
    #!/usr/bin/env bash
    echo "Running non-skippable sign-artifact stage"

scan-artifact:
  skip: true
  abort_on_failure: false
  image: icr.io/continuous-delivery/pipeline/pipeline-base-ubi:3.46
  script: |
    #!/usr/bin/env bash
    echo "Running scan-artifact stage"

deploy:
  abort_on_failure: false
  image: icr.io/continuous-delivery/pipeline/pipeline-base-ubi:3.46
  script: |
    #!/usr/bin/env bash
    echo "Running non-skippable deploy stage"

dynamic-scan:
  skip: true
  abort_on_failure: false
  image: icr.io/continuous-delivery/pipeline/pipeline-base-ubi:3.46
  script: |
    #!/usr/bin/env bash
    echo "Running dynamic-scan stage"

acceptance-test:
  skip: true
  abort_on_failure: false
  image: icr.io/continuous-delivery/pipeline/pipeline-base-ubi:3.46
  script: |
    #!/usr/bin/env bash
    echo "Running acceptance-test stage"

release:
  skip: true
  abort_on_failure: false
  image: icr.io/continuous-delivery/pipeline/pipeline-base-ubi:3.46
  script: |
    #!/usr/bin/env bash
    echo "Running release stage"

finish:
  skip: true
  abort_on_failure: false
  image: icr.io/continuous-delivery/pipeline/pipeline-base-ubi:3.46
  script: |
    #!/usr/bin/env bash
    echo "Running finish stage"
