---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ibm-commonui-operator
  namespace: {{.Values.global.operatorNamespace}}
  labels:
    app.kubernetes.io/instance: ibm-commonui-operator
    app.kubernetes.io/name: ibm-commonui-operator
