apiVersion: apps/v1
kind: Deployment
metadata:
  name: ibm-commonui-operator
  labels:
    app.kubernetes.io/instance: ibm-commonui-operator
    app.kubernetes.io/name: ibm-commonui-operator
  annotations:
    packageName: ibm-commonui-operator-app
    alm-examples: |-
      [
        {
          "apiVersion": "operators.ibm.com/v1alpha1",
          "kind": "CommonWebUI",
          "metadata": {
            "labels": {
              "app.kubernetes.io/instance": "example-commonwebui",
              "app.kubernetes.io/managed-by": "ibm-commonui-operator",
              "app.kubernetes.io/name": "ibm-commonui-operator"
            },
            "name": "example-commonwebui"
          },
          "spec": {
            "commonWebUIConfig": {
              "cpuLimits": "300",
              "cpuMemory": "256",
              "imageRegistry": "{{ .Values.imagePullPrefix }}/{{ .Values.imageRegistryNamespaceOperand }}",
              "imageTag": "4.7.0",
              "ingressPath": "/common-nav",
              "landingPage": "",
              "requestLimits": "300",
              "requestMemory": "256",
              "serviceName": "common-web-ui"
            },
            "globalUIConfig": {
              "cloudPakVersion": "3.6.0",
              "defaultAdminUser": "admin",
              "defaultAuth": "",
              "enterpriseLDAP": "",
              "enterpriseSAML": "",
              "osAuth": "",
              "sessionPollingInterval": 5000
            },
            "operatorVersion": "4.7.0",
            "replicas": 1,
            "resources": {
              "limits": {
                "cpu": "300m",
                "memory": "256Mi"
              },
              "requests": {
                "cpu": "300m",
                "memory": "256Mi",
                "ephemeral-storage": "251Mi"
              }
            },
            "version": "4.7.0"
          }
        },
        {
          "apiVersion": "foundation.ibm.com/v1",
          "kind": "NavConfiguration",
          "metadata": {
            "labels": {
              "app.kubernetes.io/instance": "common-web-ui-config",
              "app.kubernetes.io/managed-by": "ibm-commonui-operator",
              "app.kubernetes.io/name": "ibm-commonui-operator",
              "default": "true",
              "name": "common-web-ui-config"
            },
            "name": "common-web-ui-config"
          },
          "spec": {
            "about": {
              "copyright": "© 2018, 2020 IBM. All rights reserved.",
              "licenses": [
                "yq, version 3.3.0, MIT+GPL",
                "MongoDB, version 4.0.16 Community Edition, SSPL",
                "Ansible: © 2017 Red Hat, Inc., http://www.redhat.com; © Henry Graham (hzgraham) \u003cHenry.Graham@mail.wvu.edu\u003e",
                "calico-bird: © 1998–2008, Martin Mares \u003cmj@ucw.cz\u003e; © 1998–2000, Pavel Machek \u003cpavel@ucw.cz\u003e; © 1998–2008, Ondrej Filip \u003cfeela@network.cz\u003e; © 2009–2013,  CZ.NIC z.s.p.o.",
                "chrony: © Richard P. Curnow  1997-2003, GPL v2",
                "collectd, © 2017-2018, version 5.7.2, GPL v2, \u003chttps://github.com/collectd/collectd/tree/collectd-5.7.2\u003e",
                "crudini: © Pádraig Brady \u003cP@draigBrady.com\u003e",
                "Galera-3: © 2007–2014 Codership Oy \u003cinfo@codership.com\u003e",
                "glusterfs: © 2010–2013+ James Shubin \u003chttps://ttboj.wordpress.com/\u003e",
                "haproxy: © 2000–2013  Willy Tarreau \u003cw@1wt.eu\u003e",
                "heketi v6.0.0: © 2015 The heketi Authors, GPL v2",
                "heketi v8.0.0: © 2015 The heketi Authors, GPL v2",
                "heketi-master/apps.app.go: © 2015 The heketi Authors",
                "heketi-master/client/api/go-client/backup.go: © 2016 The heketi Authors",
                "heketi-master/doc/man/heketi-cli.8: © 2016 The heketi Authors",
                "heketi-master/extras/docker/gluster/gluster-setup.sh: © 2016 Red Hat, Inc. \u003chttp://www.redhat.com\u003e",
                "ieee-data: © 2013 Luciano Bello \u003cluciano@debian.org\u003e",
                "javax.mail: © 2017 Oracle and/or its affiliates. All rights reserved.",
                "keepalived: © 2001-2017 Alexandre Cassen \u003cacassen@gmail.com\u003e",
                "libonig2: © 2006–2008 Max Kellermann \u003cmax@duempel.org\u003e; © 2014–2015 Jörg Frings-Fürst \u003cdebian@jff-webhosting.net\u003e",
                "libtomcrypt: © 2004 Sam Hocevar \u003csam@hocevar.net\u003e, GPL v2",
                "mariadb-common: © 2018 MariaDB. All rights reserved.",
                "mariaDB: © 2018 MariaDB. All rights reserved. \u003chttps://mariadb.com/\u003e",
                "mariadb-server: © 2018 MariaDB. All rights reserved.",
                "minitar: © 2004 Mauricio Julio Fernandez Pradier and Austin Ziegler",
                "MongoDB: © 2007 Free Software Foundation, Inc. \u003chttp://fsf.org/\u003e",
                "nvmi-cli: © 1989, 1991 Free Software Foundation, Inc., GPL v2",
                "OpenJDK: © 2018 Oracle Corporation and/or its affiliates",
                "openshift-mariadb-galera: © 2007 Free Software Foundation, Inc. \u003chttp://fsf.org/\u003e",
                "percona-xtrabackup: © 2006–2018 Percona LLC.",
                "pwgen: © Christian Thöing \u003cc.thoeing@web.de\u003e",
                "rdoc: © 2001–2003 Dave Thomas, The Pragmatic Programmers",
                "readline: © Chet Ramey \u003cchet.ramey@case.edu\u003e",
                "John the Ripper password cracker: © 1996–2013 by Solar Designer \u003csolar@openwall.com\u003e",
                "spdx-exceptions: © 2018 SPDX Workgroup a Linux Foundation Project. All rights reserved.",
                "socat: © 2001–2010 Gerhard Rieger",
                "sshpass: © 2006, 2008 Lingnu Open Source Consulting Ltd. \u003chttp://www.lingnu.com\u003e",
                "timelimit: © 2001, 2007 - 2010  Peter Pentchev, GPL v2",
                "ua-parser-js: © 2012-2018 Faisal Salman \u003cf@faisalman.com\u003e, GPL v2",
                "ubuntu-cloud-keyring: © 2010 Michael Vogt \u003cmichael.vogt@canonical.com\u003e",
                "unboundid-ldapsdk: © 2015 UnboundID. The LDAP SDK for Java is developed by UnboundID. \u003cinfo@unboundid.com\u003e",
                "xmpp4r: © Lucas Nussbaum \u003clucas@lucas-nussbaum.net\u003e, Stephan Maka \u003cstephan@spaceboyz.net\u003e, and others.",
                "module-assistant: © 2003-2008 Eduard Bloch \u003cblade@debian.org\u003e, version 0.11.8, GPL v2; © 2009 Cyril Brulebois \u003ckibi@debian.org\u003e, version 0.11.8, GPL v2; © 2013-2018 Andreas Beckmann \u003canbe@debian.org\u003e, version 0.11.8, GPL v2",
                "module-init-tools: © 2011 ProFUSION embedded systems, version 22, GPL v2",
                "thin: © 2017 Marc-Andre Cournoyer \u003cmacournoyer@gmail.com\u003e, version 1.7.2, GPL v2",
                "gosu, © 1999-2014, version 1.1, GPL v3",
                "mercurial (Python), © 2006-2018 ,version v4.5.3, GPL v2",
                "garden-runc, © 2015-Present CloudFoundry.org Foundation, Inc. All Rights Reserved, version 1.17.0, GPLv2",
                "libtomcrypt0, © 2003-2007 Tom St Denis \u003ctomstdenis@gmail.com\u003e, version 1.17-7, GPLv2",
                "console-setup-min, © 1999,2000,2001,2002,2003,2006,2007,2008,2009,2010,2011 Anton Zinoviev, \u003canton@lml.bas.bg\u003e,version 1.108, GPLv2",
                "dracut, © 2009 Harald Hoyer \u003charald@redhat.com\u003e, version 044+3-3, GPLv2",
                "dracut-core, © 2009 Harald Hoyer \u003charald@redhat.com\u003e, version 044+3-3, GPLv2",
                "g++, version 5.4.0-6ubuntu, GPL v2",
                "libstdc++6, version 5.4.0-6ubuntu, GPL v3",
                "libstdc++-5-dev, version 5.4.0-6ubuntu, GPL v3",
                "docker-engine-selinux, version 3b5fac4, GPLv2",
                "unorm, version 1.5.0, GPL v2",
                "psmisc, version 22.20, GPL v2",
                "lvm2-devel, version 2.0.2, GPL v2",
                "nfs-utils, version 1.3, GPL v2",
                "popt-static, version 1.13, GPL v2",
                "sysvinit-tools, version 2.88, GPL v2",
                "stunnel, version 5.53, GPL v2",
                "stunnel, version 5.39, GPL v2",
                "LVM2, version 2.02.180-10.el7_6.2, GPL v2",
                "sysdig, version 2c43237, GPL",
                "chisels, version 9722dbc, GPL",
                "MongoDB, version 4.0.12, SSPL",
                "ffi (Ruby Gem), 1.11.1, GPL",
                "inotify-tools, v3.14, GPL v2",
                "logrotate, v3.8.6, GPL v2",
                "checker-qual, version 2.0.0, GPLv2",
                "ocrad-bower, v1.0.0, GPL v3",
                "Grafana, v7.5.12, AGPL",
                "IBM Semeru Runtime Open Edition binaries, GPL v2",
                "checker-compat-qual 2.5.5, GPL-2.0",
                "javax.annotation-api 1.3.1, GPL-2.0"
              ],
              "logoUrl": "IBM Cloud Pak | Administration Hub",
              "logoAltText": "IBM Cloud Pak | Administration Hub"
            },
            "header": {
              "disabledItems": [
                "createResource",
                "catalog"
              ],
              "docUrlMapping": "http://ibm.biz/cpcs_adminui",
              "logoAltText": "IBM Cloud Pak Administration Hub",
              "logoHeight": "47px",
              "logoUrl": "/common-nav/graphics/ibm-cloudpack-logo.svg",
              "logoWidth": "190px"
            },
            "login": {
              "loginDialog": {
                "acceptText": "Your acceptance text here",
                "dialogText": "You must set your dialog for this environment",
                "enable": false,
                "headerText": "Header text here"
              },
              "logoAltText": "Cloud Pak",
              "logoHeight": "47px",
              "logoUrl": "/common-nav/api/graphics/logincloudpak.svg",
              "logoWidth": "190px"
            },
            "navItems": [
              {
                "id": "providers",
                "label": "Identity providers",
                "serviceId": "webui-nav",
                "url": "/common-nav/identity-access/realms"
              }
            ]
          }
        },
        {
          "apiVersion": "foundation.ibm.com/v1",
          "kind": "NavConfiguration",
          "metadata": {
            "labels": {
              "app.kubernetes.io/instance": "icp4i",
              "app.kubernetes.io/managed-by": "ibm-commonui-operator",
              "app.kubernetes.io/name": "ibm-commonui-operator",
              "name": "icp4i"
            },
            "name": "icp4i"
          },
          "spec": {
            "header": {
              "disabledItems": [
                "createResource",
                "catalog",
                "bookmark"
              ],
              "logoAltText": "Cloud Pak for Integration",
              "logoUrl": "/common-nav/graphics/ibm-cloudpak-integration.svg"
            },
            "navItems": [
              {
                "detectionServiceName": true,
                "id": "metering",
                "label": "Metering",
                "serviceId": "metering-ui",
                "serviceName": "metering-ui",
                "url": "/metering/dashboard?ace_config={ 'showClusterData': false }\u0026dashboard=cpi.icp.main"
              },
              {
                "detectionServiceName": true,
                "id": "monitoring",
                "isAuthorized": [
                  "Administrator",
                  "ClusterAdministrator",
                  "Operator"
                ],
                "label": "Monitoring",
                "serviceId": "monitoring-ui",
                "serviceName": "ibm-monitoring-grafana",
                "target": "_blank",
                "url": "/grafana"
              },
              {
                "id": "id-access",
                "label": "Identity and access",
                "serviceId": "webui-nav"
              },
              {
                "id": "providers",
                "parentId": "id-access",
                "label": "Identity providers",
                "serviceId": "webui-nav",
                "url": "/common-nav/identity-access/realms?useNav=icp4i"
              },
              {
                "id": "teams-ids",
                "parentId": "id-access",
                "label": "Teams and service IDs",
                "serviceId": "webui-nav",
                "url": "/common-nav/identity-access/teams?useNav=icp4i"
              },
              {
                "detectionServiceName": true,
                "id": "logging",
                "label": "Logging",
                "serviceId": "kibana",
                "serviceName": "kibana",
                "target": "_blank",
                "url": "/kibana"
              },
              {
                "detectionServiceName": true,
                "id": "releases",
                "label": "Helm Releases",
                "serviceId": "catalog-ui",
                "serviceName": "catalog-ui",
                "url": "/catalog/instances?useNav=icp4i"
              },
              {
                "detectionServiceName": true,
                "id": "repos",
                "label": "Helm Repositories",
                "serviceId": "catalog-ui",
                "serviceName": "catalog-ui",
                "url": "/catalog/repositories?useNav=icp4i"
              },
              {
                "detectionServiceName": true,
                "id": "licensing",
                "label": "Licensing",
                "serviceId": "ibm-license-service-reporter",
                "url": "/license-service-reporter",
                "isAuthorized": [
                  "ClusterAdministrator",
                  "CloudPakAdministrator"
                ]
              }
            ]
          }
        },
        {
          "apiVersion": "operators.ibm.com/v1alpha1",
          "kind": "SwitcherItem",
          "metadata": {
            "name": "example-switcheritem"
          },
          "spec": {
            "cloudPakInfo": {
              "display": "Administration",
              "label": "administration-hub",
              "landingPage": "/common-nav/dashboard",
              "logoURL": ""
            }
          }
        }
      ]
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ibm-commonui-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: ibm-commonui-operator
        app.kubernetes.io/managed-by: ibm-commonui-operator
        app.kubernetes.io/name: ibm-commonui-operator
        productName: IBM_Cloud_Platform_Common_Services
        intent: projected
        name: ibm-commonui-operator
      annotations:
        productName: IBM Cloud Platform Common Services
        productID: "068a62892a1e4db39641342e592daa25"
        productMetric: FREE
        "openshift.io/scc": "restricted"
    spec:
      serviceAccountName: ibm-commonui-operator
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
                - ppc64le
                - s390x
      containers:
        - name: manager
          image: {{ .Values.imagePullPrefix }}/{{ .Values.imageRegistryNamespaceOperator }}/ibm-commonui-operator:4.7.0
          command:
          - ibm-commonui-operator
          imagePullPolicy: IfNotPresent
          imagePullSecret: {{ .Values.imagePullSecret }}
          env:
            - name: OPERATOR_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: WATCH_NAMESPACE
              valueFrom:
                configMapKeyRef:
                  name: namespace-scope
                  key: namespaces
            - name: COMMON_WEB_UI_IMAGE
              value: {{ .Values.imagePullPrefix }}/{{ .Values.imageRegistryNamespaceOperand }}/common-web-ui:4.7.0
            - name: IMAGE_PULL_SECRET
              value: {{ .Values.imagePullSecret }}
          livenessProbe:
            failureThreshold: 10
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 120
            periodSeconds: 60
            timeoutSeconds: 10
          readinessProbe:
            failureThreshold: 10
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 3
            periodSeconds: 20
            timeoutSeconds: 3
          resources:
            limits:
              cpu: 40m
              memory: 200Mi
            requests:
              cpu: 10m
              memory: 25Mi
              ephemeral-storage: 251Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
