// +build !ignore_autogenerated

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v1alpha1

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"github.ibm.com/IBMPrivateCloud/common-webui/pkg/apis/operators/v1alpha1.CommonWebUIService":       schema_pkg_apis_operators_v1alpha1_CommonWebUIService(ref),
		"github.ibm.com/IBMPrivateCloud/common-webui/pkg/apis/operators/v1alpha1.CommonWebUIServiceSpec":   schema_pkg_apis_operators_v1alpha1_CommonWebUIServiceSpec(ref),
		"github.ibm.com/IBMPrivateCloud/common-webui/pkg/apis/operators/v1alpha1.CommonWebUIServiceStatus": schema_pkg_apis_operators_v1alpha1_CommonWebUIServiceStatus(ref),
	}
}

func schema_pkg_apis_operators_v1alpha1_CommonWebUIService(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "CommonWebUIService is the Schema for the commonwebuiservices API",
				Type:        []string{"object"},
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.ibm.com/IBMPrivateCloud/common-webui/pkg/apis/operators/v1alpha1.CommonWebUIServiceSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.ibm.com/IBMPrivateCloud/common-webui/pkg/apis/operators/v1alpha1.CommonWebUIServiceStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"github.ibm.com/IBMPrivateCloud/common-webui/pkg/apis/operators/v1alpha1.CommonWebUIServiceSpec", "github.ibm.com/IBMPrivateCloud/common-webui/pkg/apis/operators/v1alpha1.CommonWebUIServiceStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_operators_v1alpha1_CommonWebUIServiceSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "CommonWebUIServiceSpec defines the desired state of CommonWebUIService",
				Type:        []string{"object"},
			},
		},
	}
}

func schema_pkg_apis_operators_v1alpha1_CommonWebUIServiceStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "CommonWebUIServiceStatus defines the observed state of CommonWebUIService",
				Type:        []string{"object"},
			},
		},
	}
}
