// +build !ignore_autogenerated

//
// Copyright 2020 IBM Corporation
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Code generated by operator-sdk. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommonWebUIConfig) DeepCopyInto(out *CommonWebUIConfig) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommonWebUIConfig.
func (in *CommonWebUIConfig) DeepCopy() *CommonWebUIConfig {
	if in == nil {
		return nil
	}
	out := new(CommonWebUIConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommonWebUIGlobalConfig) DeepCopyInto(out *CommonWebUIGlobalConfig) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommonWebUIGlobalConfig.
func (in *CommonWebUIGlobalConfig) DeepCopy() *CommonWebUIGlobalConfig {
	if in == nil {
		return nil
	}
	out := new(CommonWebUIGlobalConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommonWebUILegacyConfig) DeepCopyInto(out *CommonWebUILegacyConfig) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommonWebUILegacyConfig.
func (in *CommonWebUILegacyConfig) DeepCopy() *CommonWebUILegacyConfig {
	if in == nil {
		return nil
	}
	out := new(CommonWebUILegacyConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommonWebUIService) DeepCopyInto(out *CommonWebUIService) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommonWebUIService.
func (in *CommonWebUIService) DeepCopy() *CommonWebUIService {
	if in == nil {
		return nil
	}
	out := new(CommonWebUIService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CommonWebUIService) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommonWebUIServiceList) DeepCopyInto(out *CommonWebUIServiceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CommonWebUIService, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommonWebUIServiceList.
func (in *CommonWebUIServiceList) DeepCopy() *CommonWebUIServiceList {
	if in == nil {
		return nil
	}
	out := new(CommonWebUIServiceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CommonWebUIServiceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommonWebUIServiceSpec) DeepCopyInto(out *CommonWebUIServiceSpec) {
	*out = *in
	out.CommonUIConfig = in.CommonUIConfig
	out.GlobalUIConfig = in.GlobalUIConfig
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommonWebUIServiceSpec.
func (in *CommonWebUIServiceSpec) DeepCopy() *CommonWebUIServiceSpec {
	if in == nil {
		return nil
	}
	out := new(CommonWebUIServiceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommonWebUIServiceStatus) DeepCopyInto(out *CommonWebUIServiceStatus) {
	*out = *in
	if in.Nodes != nil {
		in, out := &in.Nodes, &out.Nodes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommonWebUIServiceStatus.
func (in *CommonWebUIServiceStatus) DeepCopy() *CommonWebUIServiceStatus {
	if in == nil {
		return nil
	}
	out := new(CommonWebUIServiceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LegacyHeaderService) DeepCopyInto(out *LegacyHeaderService) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LegacyHeaderService.
func (in *LegacyHeaderService) DeepCopy() *LegacyHeaderService {
	if in == nil {
		return nil
	}
	out := new(LegacyHeaderService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LegacyHeaderService) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LegacyHeaderServiceList) DeepCopyInto(out *LegacyHeaderServiceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LegacyHeaderService, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LegacyHeaderServiceList.
func (in *LegacyHeaderServiceList) DeepCopy() *LegacyHeaderServiceList {
	if in == nil {
		return nil
	}
	out := new(LegacyHeaderServiceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LegacyHeaderServiceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LegacyHeaderServiceSpec) DeepCopyInto(out *LegacyHeaderServiceSpec) {
	*out = *in
	out.LegacyUIConfig = in.LegacyUIConfig
	out.GlobalUIConfig = in.GlobalUIConfig
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LegacyHeaderServiceSpec.
func (in *LegacyHeaderServiceSpec) DeepCopy() *LegacyHeaderServiceSpec {
	if in == nil {
		return nil
	}
	out := new(LegacyHeaderServiceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LegacyHeaderServiceStatus) DeepCopyInto(out *LegacyHeaderServiceStatus) {
	*out = *in
	if in.Nodes != nil {
		in, out := &in.Nodes, &out.Nodes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LegacyHeaderServiceStatus.
func (in *LegacyHeaderServiceStatus) DeepCopy() *LegacyHeaderServiceStatus {
	if in == nil {
		return nil
	}
	out := new(LegacyHeaderServiceStatus)
	in.DeepCopyInto(out)
	return out
}
