# permissions for end users to view commonwebuis.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: commonwebui-viewer-role
rules:
- apiGroups:
  - operators.ibm.com
  resources:
  - commonwebuis
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operators.ibm.com
  resources:
  - commonwebuis/status
  verbs:
  - get
