# permissions for end users to edit commonwebuis.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: commonwebui-editor-role
rules:
- apiGroups:
  - operators.ibm.com
  resources:
  - commonwebuis
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operators.ibm.com
  resources:
  - commonwebuis/status
  verbs:
  - get
