# permissions for end users to view switcheritems.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: switcheritem-viewer-role
rules:
- apiGroups:
  - operators.ibm.com
  resources:
  - switcheritems
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operators.ibm.com
  resources:
  - switcheritems/status
  verbs:
  - get
