apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: navconfigurations.foundation.ibm.com
spec:
  group: foundation.ibm.com
  names:
    kind: NavConfiguration
    listKind: NavconfigurationList
    plural: navconfigurations
    singular: navconfiguration
  scope: Namespaced
  subresources:
    status: {}
  versions:
  - name: v1
    served: true
    storage: true