apiVersion: foundation.ibm.com/v1
kind: NavConfiguration
metadata:
  labels:
    default: "true"
spec:
  login:
    logoAltText: /common-nav/api/graphics/logincloudpak.svg
    logoUrl: IBM Cloud Pak
    logoWidth: 190px
    logoHeight: 47px
    loginDialog:
      enable: false
      headerText: Header text here
      dialogText: "You must set your dialog for this environment. To set the dialog: SSH into your boot/master node and run the following command: 'kubectl edit configmap platform-ui-config -n kube-system'. In the ConfigMap, locate the 'ui-config.json' parameter and find the 'loginDialog' > 'dialogText' key. Replace the default text with your dialog text, then save your changes."
      acceptText: Your acceptance text here
  header:
    logoUrl: /common-nav/api/graphics/logincloudpak.svg
    logoWidth: 190px
    logoHeight: 47px
    logoAltText: IBM Cloud Pak
  about:
    logoUrl: IBM Cloud Pak
    licenses:
      - "Ansible: © 2017 Red Hat, Inc., http://www.redhat.com; © Henry Graham (hzgraham) <Henry.Graham@mail.wvu.edu>"
      - "calico-bird: © 1998–2008, Martin Mares <mj@ucw.cz>; © 1998–2000, Pavel Machek <pavel@ucw.cz>; © 1998–2008, Ondrej Filip <feela@network.cz>; © 2009–2013,  CZ.NIC z.s.p.o."
      - "chrony: © Richard P. Curnow  1997-2003, GPL v2"
      - "collectd, © 2017-2018, version 5.7.2, GPL v2, <https://github.com/collectd/collectd/tree/collectd-5.7.2>"
      - "crudini: © Pádraig Brady <P@draigBrady.com>"
      - "Galera-3: © 2007–2014 Codership Oy <info@codership.com>"
      - "glusterfs: © 2010–2013+ James Shubin <https://ttboj.wordpress.com/>"
      - "haproxy: © 2000–2013  Willy Tarreau <w@1wt.eu>"
      - "heketi v6.0.0: © 2015 The heketi Authors, GPL v2"
      - "heketi v8.0.0: © 2015 The heketi Authors, GPL v2"
      - "heketi-master/apps.app.go: © 2015 The heketi Authors"
      - "heketi-master/client/api/go-client/backup.go: © 2016 The heketi Authors"
      - "heketi-master/doc/man/heketi-cli.8: © 2016 The heketi Authors"
      - "heketi-master/extras/docker/gluster/gluster-setup.sh: © 2016 Red Hat, Inc. <http://www.redhat.com>"
      - "ieee-data: © 2013 Luciano Bello <luciano@debian.org>"
      - "javax.mail: © 2017 Oracle and/or its affiliates. All rights reserved."
      - "keepalived: © 2001-2017 Alexandre Cassen <acassen@gmail.com>"
      - "libonig2: © 2006–2008 Max Kellermann <max@duempel.org>; © 2014–2015 Jörg Frings-Fürst <debian@jff-webhosting.net>"
      - "libtomcrypt: © 2004 Sam Hocevar <sam@hocevar.net>, GPL v2"
      - "mariadb-common: © 2018 MariaDB. All rights reserved."
      - "mariaDB: © 2018 MariaDB. All rights reserved. <https://mariadb.com/>"
      - "mariadb-server: © 2018 MariaDB. All rights reserved."
      - "minitar: © 2004 Mauricio Julio Fernandez Pradier and Austin Ziegler"
      - "MongoDB: © 2007 Free Software Foundation, Inc. <http://fsf.org/>"
      - "nvmi-cli: © 1989, 1991 Free Software Foundation, Inc., GPL v2"
      - "OpenJDK: © 2018 Oracle Corporation and/or its affiliates"
      - "openshift-mariadb-galera: © 2007 Free Software Foundation, Inc. <http://fsf.org/>"
      - "percona-xtrabackup: © 2006–2018 Percona LLC."
      - "pwgen: © Christian Thöing <c.thoeing@web.de>"
      - "rdoc: © 2001–2003 Dave Thomas, The Pragmatic Programmers"
      - "readline: © Chet Ramey <chet.ramey@case.edu>"
      - "John the Ripper password cracker: © 1996–2013 by Solar Designer <solar@openwall.com>"
      - "spdx-exceptions: © 2018 SPDX Workgroup a Linux Foundation Project. All rights reserved."
      - "socat: © 2001–2010 Gerhard Rieger"
      - "sshpass: © 2006, 2008 Lingnu Open Source Consulting Ltd. <http://www.lingnu.com>"
      - "timelimit: © 2001, 2007 - 2010  Peter Pentchev, GPL v2"
      - "ua-parser-js: © 2012-2018 Faisal Salman <f@faisalman.com>, GPL v2"
      - "ubuntu-cloud-keyring: © 2010 Michael Vogt <michael.vogt@canonical.com>"
      - "unboundid-ldapsdk: © 2015 UnboundID. The LDAP SDK for Java is developed by UnboundID.
        <info@unboundid.com>"
      - "xmpp4r: © Lucas Nussbaum <lucas@lucas-nussbaum.net>, Stephan Maka <stephan@spaceboyz.net>,
        and others."
      - "module-assistant: © 2003-2008 Eduard Bloch <blade@debian.org>, version 0.11.8,
        GPL v2; © 2009 Cyril Brulebois <kibi@debian.org>, version 0.11.8, GPL v2; © 2013-2018
        Andreas Beckmann <anbe@debian.org>, version 0.11.8, GPL v2"
      - "module-init-tools: © 2011 ProFUSION embedded systems, version 22, GPL v2"
      - "thin: © 2017 Marc-Andre Cournoyer <macournoyer@gmail.com>, version 1.7.2, GPL v2"
      - "gosu, © 1999-2014, version 1.1, GPL v3"
      - "mercurial (Python), © 2006-2018 ,version v4.5.3, GPL v2"
      - "garden-runc, © 2015-Present CloudFoundry.org Foundation, Inc. All Rights Reserved,
        version 1.17.0, GPLv2"
      - "libtomcrypt0, © 2003-2007 Tom St Denis <tomstdenis@gmail.com>, version 1.17-7, GPLv2"
      - "console-setup-min, © 1999,2000,2001,2002,2003,2006,2007,2008,2009,2010,2011 Anton
        Zinoviev, <anton@lml.bas.bg>,version 1.108, GPLv2"
      - "dracut, © 2009 Harald Hoyer <harald@redhat.com>, version 044+3-3, GPLv2"
      - "dracut-core, © 2009 Harald Hoyer <harald@redhat.com>, version 044+3-3, GPLv2"
      - "g++, version 5.4.0-6ubuntu, GPL v2"
      - "libstdc++6, version 5.4.0-6ubuntu, GPL v3"
      - "libstdc++-5-dev, version 5.4.0-6ubuntu, GPL v3"
      - "docker-engine-selinux, version 3b5fac4, GPLv2"
      - "unorm, version 1.5.0, GPL v2"
      - "psmisc, version 22.20, GPL v2"
      - "lvm2-devel, version 2.0.2, GPL v2"
      - "nfs-utils, version 1.3, GPL v2"
      - "popt-static, version 1.13, GPL v2"
      - "sysvinit-tools, version 2.88, GPL v2"
      - "stunnel, version 5.53, GPL v2"
      - "stunnel, version 5.39, GPL v2"
      - "LVM2, version 2.02.180-10.el7_6.2, GPL v2"
      - "sysdig, version 2c43237, GPL"
      - "chisels, version 9722dbc, GPL"
      - "MongoDB, version 4.0.12, SSPL"
      - "ffi (Ruby Gem), 1.11.1, GPL"
      - "inotify-tools, v3.14, GPL v2"
      - "logrotate, v3.8.6, GPL v2"
      - "checker-qual, version 2.0.0, GPLv2"
    copyright: "© 2018, 2019, 2020 IBM. All rights reserved."
    version: 1.1.0
    edition: Enterprie
    logoAltText: IBM Cloud Pak
  navItems:
    - id: "monitor-health"
      label: "Monitor Health"
      iconUrl: "/common-nav/graphics/monitor-health.svg"
    - id: "metering"
      label: "Metering"
      url: "/metering/dashboard?ace_config={ 'showClusterData': false }&dashboard=cpi.icp.main"
      namespace: "kube-system"
      serviceName: "metering-ui"
      serviceId: "metering-ui"
      parentId: "administer"
      detectionServiceName: true
    - id: "monitoring"
      label: "Monitoring"
      url: "/grafana"
      namespace: "kube-system"
      serviceName: "monitoring-prometheus"
      serviceId: "monitoring-ui"
      parentId: "monitor-health"
      target: "_blank"
      detectionServiceName: true
      isAuthorized:
        - "Administrator"
        - "ClusterAdministrator"
        - "Operator"
    - id: "releases"
      label: "Helm Releases"
      url: "/catalog/instances"
      parentId: "monitor-health"
      serviceId: "catalog-ui"
    - id: "repos"
      label: "Helm Repositories"
      url: "/catalog/repositories"
      parentId: "administer"
      serviceId: "catalog-ui"
    - id: "administer"
      label: "Administer"
      iconUrl: "/common-nav/graphics/administer.svg"
    - id: "id-access"
      label: "Identity and Access"
      url: "/common-nav/identity-access"
      parentId: "administer"
      serviceId: "webui-nav"
    - id: "logging"
      label: "Logging"
      url: "/kibana"
      serviceId: "kibana"
      target: "logging"
      serviceName: "kibana"
      namespace: "kube-system"
      detectionServiceName: true
      parentId: "administer"
