apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: commonwebuis.operators.ibm.com
spec:
  group: operators.ibm.com
  names:
    kind: CommonWebUI
    listKind: CommonWebUIList
    plural: commonwebuis
    singular: commonwebui
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: CommonWebUI is the Schema for the commonwebuis API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: CommonWebUISpec defines the desired state of CommonWebUISpec
          properties:
            commonWebUIConfig:
              description: CommonWebUIConfig defines the desired state of CommonWebUIConfig
              properties:
                cpuLimits:
                  format: int64
                  type: integer
                cpuMemory:
                  format: int64
                  type: integer
                imageRegistry:
                  type: string
                imageTag:
                  type: string
                ingressPath:
                  type: string
                requestLimits:
                  format: int64
                  type: integer
                requestMemory:
                  format: int64
                  type: integer
                serviceName:
                  type: string
              type: object
            globalUIConfig:
              description: GlobalUIConfig defines the desired state of GlobalUIConfig
              properties:
                authServiceURL:
                  type: string
                cloudPakVersion:
                  type: string
                clusterName:
                  type: string
                defaultAdminUser:
                  type: string
                defaultAuth:
                  type: string
                enterpriseLDAP:
                  type: string
                enterpriseSAML:
                  type: string
                identityProviderURL:
                  type: string
                osAuth:
                  type: string
                pullSecret:
                  type: string
                routerHTTPSPort:
                  format: int32
                  type: integer
                routerURL:
                  type: string
                sessionPollingInterval:
                  format: int32
                  type: integer
              type: object
            operatorVersion:
              type: string
          type: object
        status:
          description: CommonWebUIStatus defines the observed state of CommonWebUI
          properties:
            nodes:
              description: PodNames will hold the names of the commonwebui's
              items:
                type: string
              type: array
          required:
          - nodes
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
