apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: commonwebuiservices.operators.ibm.com
spec:
  group: operators.ibm.com
  names:
    kind: CommonWebUIService
    listKind: CommonWebUIServiceList
    plural: commonwebuiservices
    singular: commonwebuiservice
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: CommonWebUIService is the Schema for the commonwebuiservices API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: CommonWebUIServiceSpec defines the desired state of CommonWebUIServiceSpec
          properties:
            globalConfig:
              description: CommonWebUIGlobalConfig defines the desired state of CommonWebUIGlobalConfig
              properties:
                CLOUDPAK_VERSION:
                  type: string
                authServiceUrl:
                  type: string
                cfcRouterUrl:
                  type: string
                cluster_name:
                  type: string
                default_admin_user:
                  type: string
                identityProviderUrl:
                  type: string
                pullSecret:
                  type: string
                router_https_port:
                  format: int32
                  type: integer
                session_polling_interval:
                  format: int32
                  type: integer
              type: object
            operatorVersion:
              type: string
            uiconfig:
              description: CommonWebUIConfig defines the desired state of CommonWebUIConfig
              properties:
                cpuLimits:
                  type: string
                cpuMemory:
                  type: string
                imageRegistry:
                  type: string
                imageTag:
                  type: string
                ingressPath:
                  type: string
                requestLimits:
                  type: string
                requestMemory:
                  type: string
                serviceName:
                  type: string
              type: object
          type: object
        status:
          description: CommonWebUIServiceStatus defines the observed state of CommonWebUIService
          properties:
            nodes:
              description: 'INSERT ADDITIONAL STATUS FIELD - define observed state
                of cluster Important: Run "operator-sdk generate k8s" to regenerate
                code after modifying this file Add custom validation using kubebuilder
                tags: https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html'
              items:
                type: string
              type: array
          required:
          - nodes
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
