apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: cloudpakswitchers.operators.ibm.com
spec:
  group: operators.ibm.com
  names:
    kind: CloudPakSwitcher
    listKind: CloudPakSwitcherList
    plural: cloudpakswitchers
    singular: cloudpakswitcher
  scope: Cluster
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: CloudPakSwitcher is the Schema for the cloudpakswitchers API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: CloudPakSwitcherSpec defines the desired state of CloudPakSwitcher
          properties:
            cloudPakInfo:
              properties:
                display:
                  type: string
                label:
                  type: string
                landingPage:
                  type: string
                logoURL:
                  type: string
                otherLinks:
                  properties:
                    display:
                      type: string
                    label:
                      type: string
                    target:
                      type: string
                    url:
                      type: string
                  type: object
              type: object
            operatorVersion:
              type: string
            version:
              type: string
          type: object
        status:
          description: CloudPakSwitcherStatus defines the observed state of CloudPakSwitcher
          properties:
            nodes:
              description: PodNames will hold the names of the commonwebui's
              items:
                type: string
              type: array
          required:
          - nodes
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
