---
cpfs:
  imageRegistryNamespaceOperator: cpopen
  imageRegistryNamespaceOperand: cpopen/cpfs
  labels:

#The following values are expected from global scope
# global:
#   imagePullPrefix: icr.io
#   imagePullSecret: ibm-entitlement-key
#   operatorNamespace: operators
#   instanceNamespace: instance
#   tetheredNamespaces:
#   - tenant1
#   - tenant2

# Enabling this sets WATCH_NAMESPACE to look for namespace-scope ConfigMap for
# the list of namespaces. Disabling generates the comma-separated list based upon
# namespaces defined in the operatorNamespace, instanceNamespace, and tenantNamespaces
# variables.
nssEnabled: false
